#!/bin/sh

## A quick hack to deploy a generated website onto a Github repository, to be served as static content by github pages.  This is an example of a very bad shell script.

# This should only be run from the root of the gitbook project
# Replace the remote Github URL to use this on a different project

cd _book && git init && git add . && git commit -m "initial commit" && git branch -m master gh-pages && git remote add agileforce git@github.com:agileforce/heroku-workshop.git && git push -f agileforce gh-pages

